const UserActionTypes = {
	FETCH_USERS_START: 'FETCH_USERS_START',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    CREATE_USER_START: 'CREATE_USER_START',
	CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
	CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    DELETE_USER_START: 'DELETE_USER_START',
	DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
	DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    UPDATE_USER_START: 'UPDATE_USER_START',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
};

export default UserActionTypes;